### ISSUE TITLE
Nothing show while i have build an APK

### ISSUE THREAD

**Issue by kibugenzad** [KittyCookie/react-native-chartjs#1]
please help me chartjs is working very well with expo but when i build an APK it is not working nothing shown

**Comment by duwizerak** [comment]
In the library (react-native-chartjs), -> node_modules -> react-native-chartjs
edit your index.js. Change 
```
source = {
			require('./dist/index.html')
		}
```
to 
```
source= {Platform.OS == 'ios' ? require('./dist/index.html') : {uri: "file:///android_asset/dist/index.html"}}
```
copy index.html from dist folder in the library to your android assets, then build the apk again. If you are providing the whole path remember to create a dist folder in your android assets too and put index.html in it.

**Comment by yashkmochi** [comment]
@duwizerak  Thanks for this solution. You saved my time. I can't understand.. why library developers are not solving this in original repo.

**Comment by Priyankjoshi1** [comment]
@duwizerak @KittyCookie  The above solution works for android but fails in IOS when I try to make production .ipa file of it.
