### ISSUE TITLE
It's possible to use Chart.helpers and Chart.elements for customization and drawing?

### ISSUE THREAD

**Issue by alanribeirodsantos** [KittyCookie/react-native-chartjs#2]
Can i extend elements and draw it again?

**Comment by Moon-009** [comment]
@alanribeiro When using chart.js, we set the chart options by setting options like this way,  "new Chart(ctx, {type:xxx,data:xxx})".Any configuration like "{type:xxx,data:xxx}"can be passed to the chart.If the configuration works in global way, It is not supported currently.
