### ISSUE TITLE
The webpage at asset:///asset_........... could not be loaded because: net:ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by kalyanipullela** [KittyCookie/react-native-chartjs#3]
Hey,

I have created the project with expo init and used the react-native-charts-js...
Its running fine in Android Emulator but when building a signed APK for the application it throws the following error.
![ee](https://user-images.githubusercontent.com/38915385/46219221-609f5200-c364-11e8-9e50-076ad866cd7a.jpg)

Can anyone help out what is the issue?

Thanks in Advance

**Comment by gawema** [comment]
> Hey,
> 
> I have created the project with expo init and used the react-native-charts-js...
> Its running fine in Android Emulator but when building a signed APK for the application it throws the following error.
> ![ee](https://user-images.githubusercontent.com/38915385/46219221-609f5200-c364-11e8-9e50-076ad866cd7a.jpg)
> 
> Can anyone help out what is the issue?
> 
> Thanks in Advance

Hi @kalyanipullela , I am having the same issue, did you perhaps find a solution??
Thanks a lot in advance! :)

**Comment by kalyanipullela** [comment]
no @gabwesth

**Comment by Moon-009** [comment]
@gabwesth @kalyanipullela 

I'm sorry to read this late. I have a little long time no develop mobile apps. About this ,I need some time to test.

**Comment by Moon-009** [comment]
@kalyanipullela @gabwesth  Happy to tell that I found the solution. According to [https://stackoverflow.com/questions/37102662/external-html-asset-not-bundled-by-react-native-in-production-build-for-use-by-w](url), I put the index.html under the assets directory and change the source configuration as 
`source = {{uri: 'file:///android_asset/index.html'}}`
 in the "index.js", It works fine.  The asset directory is under android/app/src/main, if it doesn't exist, you need create it manually.
This works just for android release situation.
