### ISSUE TITLE
Problem: IOS real device

### ISSUE THREAD

**Issue by harrischelsea** [KittyCookie/react-native-chartjs#5]
Chart is not showing on real IOS device, but on emulator everything work great.

**Comment by Moon-009** [comment]
> Chart is not showing on real IOS device, but on emulator everything work great.

what is the system version？iOS 12？Does the problem happen when the codes are packed into the .ipa file?

**Comment by harrischelsea** [comment]
Yes, system version is IOS 12.
When I open screen with Chart, I have one warning: "Unable to open URL: file://var/containers/Bundle..."
The problem is maybe in library path or something like that.

Do you have any idea what is happening?
Thank you for your reply.

**Comment by Moon-009** [comment]
> Yes, system version is IOS 12.
> When I open screen with Chart, I have one warning: "Unable to open URL: file://var/containers/Bundle..."
> The problem is maybe in library path or something like that.
> 
> Do you have any idea what is happening?
> Thank you for your reply.

I get some answers about this in google results. In this link [https://github.com/facebook/react-native/issues/20835](url) ,someone talk about this.Maybe we can try it, in the index.js,add " originWhitelist={["file://"]}" to the \<WebView /\>.I don't have a package account of apple, so maybe you can try it locally first. Hope it helps.

**Comment by Moon-009** [comment]
> Yes, system version is IOS 12.
> When I open screen with Chart, I have one warning: "Unable to open URL: file://var/containers/Bundle..."
> The problem is maybe in library path or something like that.
> 
> Do you have any idea what is happening?
> Thank you for your reply.

According to the new wiki about webview , It required add "originWhitelist={["*"]}",maybe you can try this also.

**Comment by harrischelsea** [comment]
KittyCookie, thank you very much.

"originWhitelist={["*"]}" solved my problem.
